"""Add profile fields to User

Revision ID: 45151a593af1
Revises: 2249278e3631
Create Date: 2025-12-04 12:39:49.239419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45151a593af1'
down_revision = '2249278e3631'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=20), nullable=False, server_default='default_avatar.png'))

        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
